name = "Nightspine"
author = "Sakarias"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b475fa20b473995f3a091706cba92fa3374df6eea46e5ffd478169e30858815"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
